<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1JBSF4H" failures="1" tests="5" name="testinproject.finaltesting" time="133.343" errors="0" timestamp="2024-07-11T18:28:58 IST" skipped="0">
  <testcase classname="testinproject.finaltesting" name="fill_quote_Form_withvalid" time="21.970"/>
  <system-out/>
  <testcase classname="testinproject.finaltesting" name="fill_quote_Form_with_blank_values" time="18.030"/>
  <system-out/>
  <testcase classname="testinproject.finaltesting" name="fill_quote_Form_with_invalid_mail_format" time="15.977">
    <failure message="expected [https://www.pixlogix.com/thank-you/] but found [https://www.pixlogix.com/get-a-quote/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.pixlogix.com/thank-you/] but found [https://www.pixlogix.com/get-a-quote/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testinproject.finaltesting.fill_quote_Form_with_invalid_mail_format(finaltesting.java:120)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- fill_quote_Form_with_invalid_mail_format -->
  <system-out/>
  <testcase classname="testinproject.finaltesting" name="Only_require_field_messagecheck" time="32.572"/>
  <system-out/>
  <testcase classname="testinproject.finaltesting" name="Button_enalable_check" time="44.794"/>
  <system-out/>
</testsuite> <!-- testinproject.finaltesting -->
